### ISSUE TITLE
[Question] Possible to use fingerprint-injector without browser-pool dependency?

### ISSUE THREAD

**Issue by oliverswitzer** [apify/fingerprint-injector#20]
Hi,

I'm interested in using the `fingerprint-injector` / `fingerprint-generator` library that y'all have created, but am not sure I really need all the functionality that comes with `browser-pool`. Is there any way to use this library without depending on `browser-pool`?

Thanks!
Oliver

**Comment by JaneJeon** [comment]
Yes - I use it with raw `puppeteer` and it works brilliantly.

**Comment by petrpatek** [comment]
You can actually use it even with plain chrome devtools protocol.
