### ISSUE TITLE
Fingerprint suite monorepo

### ISSUE THREAD

**Issue by petrpatek** [apify/fingerprint-injector#25]
### Context

Nowadays, three repositories are closely tight together. In the future, we want to make the release process automated on monthly bases and add shared docusaurus docs, and this is the first step to achieving these tasks efficiently.

### Goal

The main goal of this task is to put [header-generator](`https://github.com/apify/header-generator`), [fingerprint-generator](https://github.com/apify/fingerprint-generator), and (fingerprint-injector)[https://github.com/apify/fingerprint-injector] into a monorepo called `fingerprint-suite.` 
The monorepo should have an easy and automated release flow, that allows releasing beta versions and the latest version. It would be great if we could prepare the docusaurus "integration". I would not worry about the content at this stage.

**Known issues:**

- Fingerprint injector tests are failing in CI. 
- Release flow might be trickier since the fingerprint-injector is dependent on the fingerprint generator, and the fingerprint generator is dependent on the header generator.

cc @B4nan

**Comment by B4nan** [comment]
Created the repository for you:

https://github.com/apify/fingerprint-suite

And as discussed on the call, we should use the structure from https://github.com/apify/apify-ts and for publishing we can find inspiration in https://github.com/apify/apify-shared-js.

**Comment by B4nan** [comment]
> that allows releasing beta versions and the latest version

@petrpatek So we want canary builds for each commit to master, and release stable via CI periodically, e.g. once a month?

In that case we already have canary builds set up in apify-ts repo so we can reuse that.

**Comment by petrpatek** [comment]
I can see two reasons to deploy a version.

1) periodical auto-deploy with the new data files - this will be the latest always.
2) new version of fingerprint suite - new injection methods, more attributes, or new features. These should be beta versions -we can create a develop branch and deploy betas by ci from there and on merge to master only deploy latest.

**Comment by petrpatek** [comment]
Another known issue, which is quite critical for stable deployment is the fingerprint session pairing. https://github.com/apify/browser-pool/issues/64. This kind of `SessionToken` cache is already implemented in the got-scraping library. So this should be about integrating it to the browser pool.
